inherit: true

before_commands:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

tools:

  external_code_coverage:
    timeout: 1800

  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2

  php_cpd:
    min_lines: 5
    min_tokens: 70
    enabled: true

  php_cs_fixer:
    enabled: true
    config:
      level: psr2

  php_loc:
    command: phploc
    enabled: true

  php_mess_detector:
    enabled: true
    config:
      rulesets:
        - codesize
