inherit: true

before_commands:
  - composer install --dev

tools:

  php_code_coverage: true

  php_code_sniffer:
    enabled: true
    config:
      standard: PSR1 # Built-in standards: PEAR, PHPCS, PSR1, PSR2, Squiz, Zend
      sniffs: []
      severity: ~
      error_severity: ~
      warning_severity: ~
      tab_width: ~
      encoding: ~

  php_cpd:
    min_lines: 5
    min_tokens: 70
    enabled: true

  php_cs_fixer:
    enabled: true
    config:
      level: psr1 # Allowed Values: "psr0", "psr1", "psr2", "all"

  php_loc:
    command: phploc
    enabled: true

  php_mess_detector:
    enabled: true
    config:
      rulesets:
        - codesize
